[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
axum = "0.8.1"
tokio = "1.43.0"
tower-http = "0.6.2"
serde_json = "1.0.139"


